#include "ConfigManager.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>

// Вспомогательные функции
static std::string trim(const std::string& s) {
    size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

static glm::vec3 parseVec3(const std::string& str) {
    std::istringstream iss(str);
    float x, y, z;
    iss >> x >> y >> z;
    return glm::vec3(x, y, z);
}

bool ConfigManager::loadGameConfig(const std::string& filename, GameConfig& config) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Cannot open config file: " << filename << std::endl;
        return false;
    }

    std::string line;
    while (std::getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;

        size_t equalsPos = line.find('=');
        if (equalsPos == std::string::npos) continue;

        std::string key = trim(line.substr(0, equalsPos));
        std::string value = trim(line.substr(equalsPos + 1));

        if (key == "GRID_WIDTH") config.gridWidth = std::stoi(value);
        else if (key == "GRID_DEPTH") config.gridDepth = std::stoi(value);
        else if (key == "CELL_SIZE") config.cellSize = std::stof(value);
        else if (key == "INITIAL_FOOD_COUNT") config.initialFoodCount = std::stoi(value);
        else if (key == "OBSTACLE_COUNT") config.obstacleCount = std::stoi(value);
        else if (key == "CLOUD_COUNT") config.cloudCount = std::stoi(value);
        else if (key == "BIRD_COUNT") config.birdCount = std::stoi(value);
        else if (key == "FLOWER_COUNT") config.flowerCount = std::stoi(value);

        else if (key == "SKY_COLOR") config.skyColor = parseVec3(value);
        else if (key == "FLOOR_COLOR") config.floorColor = parseVec3(value);
        else if (key == "GRID_COLOR") config.gridColor = parseVec3(value);

        else if (key == "SNAKE_HEAD_MODEL") config.snakeHeadModel = value;
        else if (key == "SNAKE_HEAD_COLOR") config.snakeHeadColor = parseVec3(value);
        else if (key == "SNAKE_HEAD_SCALE") config.snakeHeadScale = std::stof(value);

        else if (key == "SNAKE_BODY_MODEL") config.snakeBodyModel = value;
        else if (key == "SNAKE_BODY_COLOR") config.snakeBodyColor = parseVec3(value);
        else if (key == "SNAKE_BODY_SCALE") config.snakeBodyScale = std::stof(value);

        else if (key == "SNAKE_TAIL_MODEL") config.snakeTailModel = value;
        else if (key == "SNAKE_TAIL_COLOR") config.snakeTailColor = parseVec3(value);
        else if (key == "SNAKE_TAIL_SCALE") config.snakeTailScale = std::stof(value);
    }

    file.close();
    return true;
}

bool ConfigManager::saveGameConfig(const std::string& filename, const GameConfig& config) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Cannot save config file: " << filename << std::endl;
        return false;
    }

    file << "# Game Configuration File\n";
    file << "# Auto-generated by ConfigEditor\n\n";

    file << "# Game Settings\n";
    file << "GRID_WIDTH = " << config.gridWidth << "\n";
    file << "GRID_DEPTH = " << config.gridDepth << "\n";
    file << "CELL_SIZE = " << config.cellSize << "\n";
    file << "INITIAL_FOOD_COUNT = " << config.initialFoodCount << "\n";
    file << "OBSTACLE_COUNT = " << config.obstacleCount << "\n";
    file << "CLOUD_COUNT = " << config.cloudCount << "\n";
    file << "BIRD_COUNT = " << config.birdCount << "\n";
    file << "FLOWER_COUNT = " << config.flowerCount << "\n\n";

    file << "# Colors\n";
    file << "SKY_COLOR = " << config.skyColor.r << " " << config.skyColor.g << " " << config.skyColor.b << "\n";
    file << "FLOOR_COLOR = " << config.floorColor.r << " " << config.floorColor.g << " " << config.floorColor.b << "\n";
    file << "GRID_COLOR = " << config.gridColor.r << " " << config.gridColor.g << " " << config.gridColor.b << "\n\n";

    file << "# Snake Appearance\n";
    file << "SNAKE_HEAD_MODEL = " << config.snakeHeadModel << "\n";
    file << "SNAKE_HEAD_COLOR = " << config.snakeHeadColor.r << " " << config.snakeHeadColor.g << " " << config.snakeHeadColor.b << "\n";
    file << "SNAKE_HEAD_SCALE = " << config.snakeHeadScale << "\n\n";

    file << "SNAKE_BODY_MODEL = " << config.snakeBodyModel << "\n";
    file << "SNAKE_BODY_COLOR = " << config.snakeBodyColor.r << " " << config.snakeBodyColor.g << " " << config.snakeBodyColor.b << "\n";
    file << "SNAKE_BODY_SCALE = " << config.snakeBodyScale << "\n\n";

    file << "SNAKE_TAIL_MODEL = " << config.snakeTailModel << "\n";
    file << "SNAKE_TAIL_COLOR = " << config.snakeTailColor.r << " " << config.snakeTailColor.g << " " << config.snakeTailColor.b << "\n";
    file << "SNAKE_TAIL_SCALE = " << config.snakeTailScale << "\n";

    file.close();
    return true;
}

bool ConfigManager::loadObstacles(const std::string& filename, std::vector<ObstacleData>& obstacles) {
    std::ifstream file(filename, std::ios::binary);
    if (!file.is_open()) return false;

    size_t count;
    file.read((char*)&count, sizeof(count));

    obstacles.clear();
    obstacles.reserve(count);

    for (size_t i = 0; i < count; i++) {
        ObstacleData obs;

        size_t len;
        file.read((char*)&len, sizeof(len));
        obs.name.resize(len);
        file.read(&obs.name[0], len);

        file.read((char*)&len, sizeof(len));
        obs.modelFile.resize(len);
        file.read(&obs.modelFile[0], len);

        file.read((char*)&obs.sizeX, sizeof(obs.sizeX));
        file.read((char*)&obs.sizeY, sizeof(obs.sizeY));
        file.read((char*)&obs.sizeZ, sizeof(obs.sizeZ));
        file.read((char*)&obs.color, sizeof(obs.color));
        file.read((char*)&obs.spawnChance, sizeof(obs.spawnChance));
        file.read((char*)&obs.minDistanceFromStart, sizeof(obs.minDistanceFromStart));

        obstacles.push_back(obs);
    }

    file.close();
    return true;
}

bool ConfigManager::saveObstacles(const std::string& filename, const std::vector<ObstacleData>& obstacles) {
    std::ofstream file(filename, std::ios::binary);
    if (!file.is_open()) return false;

    size_t count = obstacles.size();
    file.write((char*)&count, sizeof(count));

    for (const auto& obs : obstacles) {
        size_t len = obs.name.length();
        file.write((char*)&len, sizeof(len));
        file.write(obs.name.c_str(), len);

        len = obs.modelFile.length();
        file.write((char*)&len, sizeof(len));
        file.write(obs.modelFile.c_str(), len);

        file.write((char*)&obs.sizeX, sizeof(obs.sizeX));
        file.write((char*)&obs.sizeY, sizeof(obs.sizeY));
        file.write((char*)&obs.sizeZ, sizeof(obs.sizeZ));
        file.write((char*)&obs.color, sizeof(obs.color));
        file.write((char*)&obs.spawnChance, sizeof(obs.spawnChance));
        file.write((char*)&obs.minDistanceFromStart, sizeof(obs.minDistanceFromStart));
    }

    file.close();
    return true;
}